FROM alpine:3.10.1

WORKDIR /src/webapp

# Install base dependencies
RUN apk update && \
    apk add --no-cache nodejs npm

# Copy settings
COPY src/webapp/package.json /src/webapp/package.json
COPY src/webapp/.babelrc /src/webapp/.babelrc
COPY src/webapp/webpack.config.js /src/webapp/webpack.config.js

RUN npm install
